polls/urls.py
from django.conf.urls import url
from django.urls import include, path

import django.contrib.auth.views

from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import logout_then_login
from django.contrib.auth import views as auth_views
from django.conf.urls import include
from django_filters.views import FilterView
from .filters import FiltroQuestoes
from rest_framework import routers
from .views import QuestaoViewset, ProvaViewset,ProvaQuestaoViewset


router = routers.DefaultRouter()
router.register(r'questao',QuestaoViewset)
router.register(r'prova',ProvaViewset)

from django.conf.urls import (handler400, handler403, handler404, handler500)

handler400 = 'polls.views.bad_request'
handler403 = 'polls.views.permission_denied'
handler404 = 'polls.views.page_not_found'
handler500 = 'polls.views.server_error'


urlpatterns = [
	url(r'^registrar/$', views.registrar, name='registrar'),
	url(r'^api/',include(router.urls)),
	#url('^', include('django.contrib.auth.urls')),
	url(r'^select2/', include('django_select2.urls')),
	url(r'^test',views.get_data,name="getdata"),
	url(r'^$', views.index,name='index'),
	url(r'^registrar/$', views.registrar,name='registrar'),
	#url(r'^quiz/$', views.quiz,name='quiz'),
	path('quiz/', views.quiz, name='quiz'),
	url(r'^quiz/selecionar$', views.seletor_quiz,name='seletor_quiz'),
	url(r'^login/$', LoginView.as_view(template_name='polls/login.html'), name="login"),
	url(r'^logout/$', logout_then_login,{'login_url': '/login/'},name='logout'),
	url(r'^alterarsenha/$', views.alterarsenha, name='alterarsenha'),
	url(r'^perfil/$', views.profile_view, name='profile'),
	url(r'^perfil/editarperfil/$', views.edit_profile, name='edit_profile'),
	path('filter_dropdown2/', views.filter_dropdown2, name='filter_dropdown2'),
	path('questoes/ajax/', views.questoes_ajax, name='questoes_ajax'),
	path('questoes/choices/ajax/',views.questoes_choices_ajax,name='questoes_choices_ajax'),
	url(r'^questoes/nova/',views.add_questoes,name="add_questoes"),
	url(r'^questoes/lista_aprovacao/',views.lista_aprovacao,name="lista_aprovacao"),
	url(r'^provas/nova/',views.add_provas,name="add_provas"),
	path('categorias/ajax/', views.categorias_ajax, name='categorias_ajax'),
	path('categorias/choices/ajax/',views.categorias_choices_ajax,name='categorias_choices_ajax'),
	url(r'^categorias/nova/',views.add_categorias,name="add_categorias"),
	url(r'^pesquisa/$', views.pesquisa),
	url(r'^desempenho/$', views.desempenho,name='desempenho'),
	url(r'^desempenho_alunos/$', views.desempenho_disciplinas,name='desempenho_disciplinas'),
	#url(r'^thanks/$', views.thanks,name='thanks'),
	#url(r'^(?P<idProva>[-_\w]+)/(?P<idQuestao>[-_\w]+)/resposta/$', views.resposta, name='resposta'),
	url('<int:pk>/resultado/', views.resultado, name='resultado'),
	#url(r'^(?P<idCategoria>[-_\w]+)/$', views.categoria, name='categoria'),
	url(r'^(?P<idProva>[-_\w]+)/(?P<idQuestao>\w+)/$', views.questoes,name="questoes"),
	url(r'^(?P<idProva>[-_\w]+)/$', views.detalhes,name='detalhes'),
	#path('lista_de_questoes/', views.lista_de_questoes, name='lista_de_questoes'),
	#path('ajax/load-questoes/', views.load_questoes, name='ajax_load_questoes'),
	#path('ajax/load-categorias/', views.load_categorias, name='ajax_load_categorias'),
	#url(r'^(?P<idProva>\w+)/$', views.resultados, name ='resultados'),
	#url(r'^(?P<idProva>\w+)/resultados/$', views.resultados, name='resultados'),
	#url(r'^(?P<idProva>\w+)/(?P<idQuestao>\w+)$', views.resposta, name='resposta'),
	#url(r'^(?P<idProva>\w+)/(?P<idQuestao>\w+)/(?P<idOpcao>\w+)/$', views.detalhes, name ='detalhes'),
	#url(r'^(?P<idProva>\w+)/$', views.detalhes, name='resposta'),
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.conf.urls import url, include
from django.contrib import  admin
from polls import views

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^', include('polls.urls')),
	url(r'^chaining/', include('smart_selects.urls')),
]

polls/models.py
import re

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
import json
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.core import validators
from django.dispatch import receiver
from django.core.exceptions import ObjectDoesNotExist
from django.utils.translation import ugettext_lazy as _
from django.utils.safestring import mark_safe
from django.template.loader import render_to_string
from django.db.models import Q

UM = 1
DOIS = 2		

class Prova(models.Model):
	idProva = models.CharField(max_length=5,primary_key=True,null=False,verbose_name="ID da prova")
	TIPO_PROVA_CHOICES = (
       ('ENADE','ENADE'),
       ('PROFMAT','PROFMAT'),
    )
	tipoProva = models.CharField(max_length=7,choices=TIPO_PROVA_CHOICES,null=False,verbose_name="Tipo da prova")
	anoProva = models.CharField(max_length=4,null=False,verbose_name="Ano da prova")
	def __str__(self):
		return self.idProva
		verbose_name_plural = "Provas"

class Categoria(models.Model):
	idCategoria = models.CharField(primary_key=True,max_length=12,null=False,default='Categoria',verbose_name="ID da Categoria")
	nomeCategoria = models.CharField(max_length=30,null=False,verbose_name="Categoria")
	parent = models.ForeignKey('self',blank=True, null=True ,related_name='materias', on_delete=models.CASCADE)
	def __str__(self):
		return self.nomeCategoria
		verbose_name_plural = "Categorias"
	@property
	def get_categoria(self):
		return Questao.objects.filter(categoria__idCategoria=self.idCategoria)

class Questao(models.Model):
	idQuestao = models.CharField(max_length=7,primary_key=True,null=False,verbose_name="ID da questão")
	idProva = models.ForeignKey(Prova,on_delete=models.CASCADE,verbose_name="Prova")
	idCategoria = models.ManyToManyField(Categoria,default="Categorias",verbose_name="Categoria")
	textoQuestao = models.CharField(max_length=2000,blank=True,null=True,verbose_name="Texto da questão")
	imagemQuestao = models.FileField(upload_to='static/img/uploads',blank=True,null=True,verbose_name="Imagem da questão")
	imagem2Questao = models.FileField(upload_to='static/img/uploads',blank=True,null=True,verbose_name="Imagem 2 da questão")
	perguntaQuestao = models.CharField(max_length=500,blank=True,null=True,verbose_name="Pergunta da questão")
	aOpcao = models.CharField(max_length=500,null=False,blank=True,verbose_name="Letra a")
	bOpcao = models.CharField(max_length=500,null=False,blank=True,verbose_name="Letra b")
	cOpcao = models.CharField(max_length=500,null=False,blank=True,verbose_name="Letra c")
	dOpcao = models.CharField(max_length=500,null=False,blank=True,verbose_name="Letra d")
	eOpcao = models.CharField(max_length=500,null=False,blank=True,verbose_name="Letra e")
	ajuda = models.CharField(max_length=500,verbose_name="Ajuda da questão",null=True,default="",blank=True)
	RESPOSTA_CHOICES = (
		('A','A'),
		('B','B'),
		('C','C'),
		('D','D'),
		('E','E'),
	)
	respostaQuestao = models.CharField(max_length=1,choices=RESPOSTA_CHOICES,verbose_name="Resposta da questão")
	STATUS_QUESTAO_CHOICES = (
		(UM,'Ativa'),
		(DOIS,'Inativa'),
	)
	statusQuestao = models.IntegerField('Status de questão',choices=STATUS_QUESTAO_CHOICES,null=False)
	QUESTAO_CHOICES = (
		(UM,'Múltipla escolha'),
		(DOIS,'Discursiva'),
	)
	tipoQuestao = models.IntegerField('Tipo de questão',choices=QUESTAO_CHOICES,null=False)
	def categorias(self):
		return "\n".join([p.nomeCategoria for p in self.idCategoria.all()])
	def __str__(self):
		return self.idQuestao
	def __unicode__(self):
		return self.idQuestao
	class Meta:
		verbose_name = "Questão"
		verbose_name_plural = "Questões"

class Resposta(models.Model):
	idQuestao = models.ForeignKey(Questao,on_delete=models.CASCADE,verbose_name="ID da questão")
	usuario = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name="Usuário")
	RESPOSTA_CHOICES = (
		('A','A'),
		('B','B'),
		('C','C'),
		('D','D'),
		('E','E'),
	)
	resposta = models.CharField(max_length=1,choices=RESPOSTA_CHOICES,verbose_name="Resposta")
	respostaA = models.CharField(max_length=2000,blank=True,null=True,verbose_name="Resposta da letra a")
	respostaB = models.CharField(max_length=2000,blank=True,null=True,verbose_name="Resposta da letra b")
	respostaC = models.CharField(max_length=2000,blank=True,null=True,verbose_name="Resposta da letra c")
	respostaD = models.CharField(max_length=2000,blank=True,null=True,verbose_name="Resposta da letra d")
	respostaE = models.CharField(max_length=2000,blank=True,null=True,verbose_name="Resposta da letra e")
	certaresposta = models.BooleanField(default=False)
	def __str__(self):
		return self.resposta
	def get_respostas(self):
		return self.resposta_set.filter(usuario=request.user)
	class Meta:
		verbose_name = "Resposta"
		verbose_name_plural = "Respostas"

class Usuario(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE,verbose_name="Usuário")
	matricula = models.CharField('Matrícula',max_length=12,unique=True,null=False,help_text=_('São requeridos os 12 dígitos referentes à sua matrícula da UERJ'), validators=[ validators.RegexValidator(re.compile('^[0-9]{12}$'), _('Digite uma matrícula válida'), _('invalid'))])
	avatar = models.ImageField('Foto de perfil',upload_to='static/img/uploads/profile_photo',default="static/img/user.jpg")
	pontos = models.IntegerField(verbose_name="Pontuação",default=0)
	idCategoria = models.ManyToManyField(Categoria,default="Categorias",verbose_name="Categoria") 
	USUARIO_CHOICES = (
		(UM,'Aluno'),
		(DOIS,'Professor'),
	)
	tipoUsuario = models.IntegerField('Tipo de Usuário',choices=USUARIO_CHOICES,default=1)
	class Meta:
		verbose_name = "Usuário"
		verbose_name_plural = "Usuários"
	def image_tag(self):
		if self.avatar:
			return mark_safe('<img src="%s" style="width: 45px; height:45px;" />' % self.avatar.url)
		else:
			return 'Sem imagem'
	image_tag.short_description = 'Imagem'
	def thumbnail(self):
		return render_to_string('polls/edit_profile.html', {'image': self})
@receiver(post_save, sender=User)
def update_user_usuario(sender, instance, created, **kwargs):
	if created:
		Usuario.objects.create(user=instance)
	instance.usuario.save()
@receiver(post_save, sender=User)
def update_user_usuario(sender, instance, created, **kwargs):
	if created:
		Usuario.objects.create(user=instance)
	instance.usuario.save()

prova/polls/forms/forms.py
from django import forms

from polls.models import Prova, Usuario, Questao, Opcao, Resposta, Historico

# class ProvaForm(forms.ModelForm)
# 	tipoProva = forms.CharField(label='Tipo da Prova',max_length=5,null=False)
# 	anoProva = forms.CharField(label='Ano da Prova',max_length=4,null=False)
# 	class Meta:
# 		model = Prova

class UsuarioForm(forms.ModelForm):
	matriculaUsuario = forms.CharField(label='Matrícula do Usuário',max_length=12)
	nomeUsuario = forms.CharField(label='Nome do Usuário',max_length=200)
	emailUsuario = forms.EmailField(label='E-mail')
	tipoUsuario = forms.CharField(label='1 - Aluno 2 - Professor',max_length=1)
	senhaUsuario = forms.CharField(max_length=20)
	class Meta:
		model = Usuario
		fields = ('matriculaUsuario','nomeUsuario','emailUsuario','tipoUsuario')

# class QuestaoForm(forms.ModelForm)
# 	textoQuestao = forms.CharField(label='Texto da questão')
# 	imagemQuestao = forms.ImageField()
# 	perguntaQuestao = forms.CharField(label='Pergunta da questão',null=False)
# 	class Meta:
# 		model = Questao

# class OpcaoForm(forms.ModelForm)
# 	class Meta:
# 		model = Opcao

# class RespostaForm(forms.ModelForm)
	
# 	class Meta:
# 		model = Resposta

# class HistoricoForm(forms.ModelForm)
# 	class Meta:
# 		model = Historico

polls/templates/polls/add_provas.html
{% extends "polls/base.html" %}
{% load widget_tweaks %}
{% block content %}
    {% if user.is_authenticated %}
    {% if user.usuario.tipoUsuario == 2 %}
	<div class="col-md-12">
	<h1 class="display-3 text-center text-primary">Adicionar nova prova</h1>
	<form id="form" method='POST' action="">
		{% csrf_token %}
	{% for field in form %}
    <div class="form-group">
        {{ field.label_tag }} 
        {% if form.is_bound %} 
            {% if field.errors %} 
                {% render_field field class="form-control is-invalid" %} 
                {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{error}}
                    </div>
                {% endfor %} 
            {% else %} 
                {% render_field field class="form-control is-valid" %} 
            {% endif %} 
        {% else %} 
            {% render_field field class="form-control" %} 
        {% endif %} 

        {% if field.help_text %}
            <small class="form-text text-muted">
               {{ field.help_text }}
            </small>
        {% endif %}
    </div>
    {% endfor %}
	<input class="btn btn-primary btn-block" type="submit" value="Salvar">
</form>
</div>
{% else %}
    <div class="alert alert-danger text-center" role="alert"><strong>Sua conta não tem acesso à essa página.</strong></div>
{% endif %}
{% else %}
    <div class="alert alert-danger text-center" role="alert"><strong>Sua conta não tem acesso à essa página.</strong></div>
{% endif %}
{% endblock %}

polls/templates/polls/add_questoes.html
{% extends "polls/base.html" %}
{% load widget_tweaks %}
{% block content %}
{% if user.is_authenticated %}
    {% if user.usuario.tipoUsuario == 2 %}
	<div class="col-md-12">
	<h1 class="display-3 text-center text-primary">Adicionar nova questão</h1>
	<form id="form" method='POST' action="">
		{% csrf_token %}
	{% for field in form %}
    <div class="form-group">
        {{ field.label_tag }} 
        {% if form.is_bound %} 
            {% if field.errors %} 
                {% render_field field class="form-control is-invalid" %} 
                {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{error}}
                    </div>
                {% endfor %} 
            {% else %} 
                {% render_field field class="form-control is-valid" %} 
            {% endif %} 
        {% else %} 
            {% render_field field class="form-control" %} 
        {% endif %} 

        {% if field.help_text %}
            <small class="form-text text-muted">
               {{ field.help_text }}
            </small>
        {% endif %}
    </div>
    {% endfor %}
	<input class="btn btn-primary btn-block" type="submit" value="Salvar">
</form>
</div>
{% else %}
    <div class="alert alert-danger text-center" role="alert"><strong>Sua conta não tem acesso à essa página.</strong></div>
{% endif %}
{% else %}
    <div class="alert alert-danger text-center" role="alert"><strong>Sua conta não tem acesso à essa página.</strong></div>
{% endif %}
{% endblock %}

polls/templates/polls/alertaquiz.html
{% extends "polls/base.html" %}
{% block title %}{% endblock %}
{% load widget_tweaks %}
{% block content %}
	

{{contagem_resp}}
{{questao}}
{{prova}}


	Oi
{% endblock %}

polls/templates/polls/base.html
<!DOCTYPE html>
<head>
{% load static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js" type="text/javascript"></script>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<script src="{% static 'js/app.js' %}" async></script>
<script src="{% static 'js/jquery-3.4.1.min.js' %}" async></script>
<link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>  
<link rel="stylesheet" type="text/css" href="{% static '/css/polls.css' %}" />
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="shortcut icon" href="{%  static 'img/favicon.png' %}">
<script src="{% static 'smart-selects/admin/js/chainedfk.js' %}"></script>
<script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
<script type="text/javascript" src="http://yourjavascript.com/7174319415/script.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<html lang="en">
<br><br><br>
<nav class="navbar navbar-findcond navbar-fixed-top">
    <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><img style="width: 32px;height: 32px;" src="/static/img/favicon.png"> Página Inicial</a>
      <title>{% block head_title %}</title>{% endblock %}
    </div>
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
            <li><a href="/perfil"><span class="glyphicon glyphicon-user"></span> Perfil</a></li></a></li>
        {% if user.is_superuser %}
            <li><a href="/admin"><i class="fa fa-server"></i> Área do Aministrador</a></li></a></li>
        {% endif %}
            <li><a href="/logout"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
        {% else %}
          <li><a href="/registrar"><span class="glyphicon glyphicon-log-in"></span> Cadastro</a></li>
        {% endif %}
            </ul>
          </div>
        </div>
      </nav>

    </head>
    <body>
      <div class="container">
        <div class="right">
          <h1>{% block title %}{% endblock %}</h1>
          {% block content %}
            {% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li class="{{ message.tags }}">{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}
          {% endblock %}
        </div>
      </div>
    {% block javascript %}{% endblock %}
    </body>
</html>

polls/templates/polls/detalhes.html
{% extends 'polls/base.html' %}

{% block content %}

{% if user.is_authenticated %}

{% if prova.questao_set.all and user  %}
  <h1 class="display-3 text-center text-primary">{{prova.tipoProva}} {{prova.anoProva}}</h1>
  <div align="center"><img src="/static/img/{{prova}}.png"></div>
   <ul id="questoes">
     {% for questao in prova.questao_set.all %}
       <hr id="linha" />
        {% if questao.statusQuestao == 1 %}
          <h3 style="text-align: center;text-transform: uppercase;color: #00008B;;">Questão {{questao.idQuestao}}</h3><h4>{% for c in questao.idCategoria.all %}<span class="label label-success"><a href="/categorias/{{c.idCategoria}}" style="color:#FFFFFF">{{c}} </a></span>{% endfor %}</h4>
          {% if questao.textoQuestao is not None %}
            <p>{{questao.textoQuestao}}</p>
          {% endif %}
          {% if questao.imagemQuestao %}
             <div class="col-xs-15" align="center">
                <img class="img-responsive" id="myImg1" src="/{{questao.imagemQuestao}}" style="width:100%;max-width:300px">
                <br>
            </div>
          {% endif %}
          {% if questao.imagem2Questao %}
            <div class="col-xs-15" align="center">
                <img class="img-responsive" id="myImg2" src="/{{questao.imagem2Questao}}" style="width:100%;max-width:300px">
                <br>
            </div>
          {% endif %}
          {% if questao.perguntaQuestao %}
            <p>{{questao.perguntaQuestao}}</p>
          {% endif %}
          {% if questao.aOpcao %}
             A) {{questao.aOpcao}}<br>
              {% endif %}
              {% if questao.bOpcao %}
             B) {{questao.bOpcao}}<br>
              {% endif %}
              {% if questao.cOpcao %}
             C) {{questao.cOpcao}}<br>
              {% endif %}
              {% if questao.dOpcao %}
             D) {{questao.dOpcao}}<br>
              {% endif %}
              {% if questao.eOpcao %}
             E) {{questao.eOpcao}}<br>
              {% endif %}
            <a class="btn-block btn btn-primary btn-md" href="/{{questao.idProva}}/{{questao.idQuestao}}" role="button">Visualizar questão</a>
      {% else %}
        <div class="alert alert-danger text-center" role="alert"><strong>Questão {{questao.idQuestao}} indisponível.</strong></div>
        <a class="btn-block btn btn-primary btn-md" href="/{{questao.idProva}}/{{questao.idQuestao}}" role="button">Analisar aprovação</a>
      {% endif %}
    {% endfor %}
    </ul>
  {% else %}
    <div class="alert alert-danger text-center" role="alert"><strong>Não há questões nesta prova.</strong></div>
        {% endif %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>{% else %}
  <h1 class="alert alert-danger text-center" role="alert">Não há questões para serem exibidas.</h1>
{% endif %}

{% else %}
  <h1 class="alert alert-danger text-center" role="alert">Se autentifique para poder acessar a questão.</h1>
{% endif %}
{% endblock %}

polls/templates/polls/edit_profile.html
{% extends "polls/base.html" %}

{% load widget_tweaks %}

{% block content %}

<script type="text/javascript">
    function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#myimg').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
    }
}

$(function () { //document ready call
    $("#id_avatar").change(function(){
        readURL(this);
    });
});
  </script>


<form method="POST" action="{% url 'edit_profile' %}" class="" enctype="multipart/form-data">
	<div id="login-overlay" class="modal-dialog">
	<div class="modal-content">
	<div class="modal-header">
			 <h4 class="modal-title" id="myModalLabel">Editar perfil</h4>
		 </div>
	<div class="modal-body">
			 <div class="row">
          <div align="center"> <img id="myimg" alt="Foto de perfil" src="/{{user.usuario.avatar}}" class="img-circle img-responsive" style="height: 263px;width: 263px;"> </div>
			   <div class="col-xs-12">
  {% csrf_token %}

   {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
  {% endfor %}

  {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
  {% endif %}

  {% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}
      {% if form.is_bound %}
        {% if field.errors %}
          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% else %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
        {% render_field field class="form-control" %}
      {% endif %}
      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
  {% endfor %}
  {% for field in profile_form.visible_fields %}
    <div class="form-group">
      {% if profile_form.is_bound %}
        {% if field.errors %}
          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% else %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
       {% if field.name == 'idCategoria' %}
       {% if request.user.usuario.tipoUsuario == 1 %}
       <div style="display: none;" id="hidden_div">
         {{ field.label_tag }}<br>
         {{ field|add_class:'form-control' }}
       </div>
       {% else %}
       <div id="hidden_div">
         {{ field.label_tag }}<br>
         {{ field|add_class:'form-control' }}
       </div>
       {% endif %}
       {% else %}
       {{ field.label_tag }}<br>
       {{ field|add_class:'form-control' }}
       {% endif %}
      {% endif %}

      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
  {% endfor %}

  <button type="submit" class="btn btn-primary">Atualizar perfil</button>
  </div>
			</div>
		</div>
	</div>
</div>

</form>


{% endblock %}

polls/templates/polls/logout.html
{% extends "base.html" %}

{% block content %}
<p>Logged out!</p>  

<a href="{% url 'login'%}">Click here to login again.</a>
{% endblock %}

polls/templates/polls/resultado.html
<h1>{{ questao.textoQuestao }}</h1>

<ul>
{% for resposta in questao.resposta_set.all %}
    <li>{{ resposta.resposta }} -- {{ resposta.idResposta }} resposta{{ resposta.idResposta|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>